In [2]:
import sqlite3
import pandas as pd

In [40]:
conn = sqlite3.connect("D:\\apexplanet-data-analytics\\database\\superstore.db")
cursor = conn.cursor()

In [4]:
df = pd.read_csv("D:\\apexplanet-data-analytics\\data\\cleaned_superstore.csv")

In [6]:
df.to_sql("superstore", conn, if_exists = "replace", index = False)

9011

In [7]:
pd.read_sql("Select * From superstore limit 5", conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [9]:
pd.read_sql("SELECT * FROM superstore", conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9006,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
9007,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
9008,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
9009,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
9010,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [16]:
pd.read_sql("SELECT * FROM superstore WHERE \"Country/Region\" = 'United States'",conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8819,10189,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10002103,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",13.904,2,0.2,4.5188
8820,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
8821,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
8822,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
8823,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279

In [19]:
pd.read_sql("SELECT * FROM superstore ORDER BY Sales DESC limit 10",conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,411,US-2023-118976,2023-04-28,2023-05-03,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Baltimore,...,21215,East,OFF-ST-10000877,Office Supplies,Storage,Recycled Steel Personal File for Standard File...,497.610,9,0.0,129.3786
1,6448,US-2025-156748,2025-11-30,2025-12-06,Standard Class,BS-11755,Bruce Stewart,Consumer,United States,Detroit,...,48227,Central,OFF-ST-10001370,Office Supplies,Storage,Sensible Storage WireTech Storage Systems,496.860,7,0.0,24.8430
2,6417,US-2025-126893,2025-11-26,2025-12-01,Standard Class,CT-11995,Carol Triggs,Consumer,United States,Philadelphia,...,19134,East,TEC-PH-10004165,Technology,Phones,Mitel MiVoice 5330e IP Phone,494.982,3,0.4,-115.4958
3,2934,US-2024-163237,2024-08-07,2024-08-09,Second Class,EM-14095,Eudokia Martin,Corporate,United States,Springfield,...,22153,South,TEC-PH-10003601,Technology,Phones,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970,3,0.0,148.4910
4,10107,US-2026-162670,2026-12-23,2026-12-28,Second Class,MF-18250,Monica Federle,Corporate,United States,Little Rock,...,72209,South,TEC-PH-10003601,Technology,Phones,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970,3,0.0,148.4910
5,4019,US-2024-157770,2024-12-13,2024-12-15,First Class,RD-19585,Rob Dowd,Consumer,United States,Temecula,...,92592,West,TEC-PH-10001530,Technology,Phones,Plantronics Voyager Pro Legend,494.376,3,0.2,49.4376
6,5224,US-2025-100720,2025-07-16,2025-07-21,Standard Class,CK-12205,Chloris Kastensmidt,Consumer,United States,Philadelphia,...,19120,East,TEC-PH-10003963,Technology,Phones,GE 2-Jack Phone Line Splitter,494.376,4,0.4,-115.3544
7,2173,US-2024-104129,2024-02-27,2024-03-02,Standard Class,ES-14080,Erin Smith,Corporate,United States,Providence,...,2908,East,FUR-TA-10004152,Furniture,Tables,"Barricks 18"" x 48"" Non-Folding Utility Table w...",493.920,7,0.3,-28.2240
8,1160,US-2023-120411,2023-09-20,2023-09-23,First Class,SB-20185,Sarah Brown,Consumer,United States,Chicago,...,60653,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,493.430,5,0.3,-70.4900
9,6072,US-2025-119165,2025-10-31,2025-11-06,Standard Class,BD-11320,Bill Donatelli,Consumer,United States,Philadelphia,...,19143,East,FUR-CH-10000988,Furniture,Chairs,Hon Olson Stacker Stools,492.835,5,0.3,-14.0810

In [23]:
pd.read_sql("SELECT Category, SUM(Sales) As TOTAL_SALES FROM superstore GROUP BY Category", conn)

          Category  TOTAL_SALES
0        Furniture  253368.5264
1  Office Supplies  349183.1640
2       Technology  230456.6190

In [24]:
pd.read_sql("SELECT Category, SUM(Sales) As TOTAL_SALES FROM superstore GROUP BY Category HAVING TOTAL_SALES > 300000", conn)

          Category  TOTAL_SALES
0  Office Supplies   349183.164

In [29]:
pd.read_sql("SELECT \"Product Name\", Sales FROM superstore WHERE Sales > (SELECT AVG(Sales) FROM superstore);", conn)

                                           Product Name    Sales
0                         SAFCO Boltless Steel Shelving  272.736
1                                           GE 30524EE4  391.980
2         O'Sullivan Elevations Bookcase, Cherry Finish  333.999
3     Logitech 910-002974 M325 Wireless Mouse for We...  149.950
4               DAX Black Cherry Wood-Tone Poster Frame  127.104
...                                                 ...      ...
2798                                         Xerox 1915  209.700
2799                                   Adtran 1202752G1  302.376
2800                            Nu-Dell Executive Frame   99.120
2801  Bush Westfield Collection Bookcases, Fully Ass...  323.136
2802  Eureka The Boss Plus 12-Amp Hard Box Upright V...  209.300

[2803 rows x 2 columns]

In [32]:
pd.read_sql("WITH high_sales AS (SELECT \"Order ID\", Sales, Profit FROM superstore WHERE Sales > 300) SELECT * FROM high_sales;", conn)

           Order ID    Sales    Profit
0    US-2023-167199  391.980  113.6742
1    US-2023-157147  333.999    3.9294
2    US-2023-155502  489.920    0.0000
3    US-2023-117163  333.000  -16.6500
4    US-2023-140795  468.900  206.3160
..              ...      ...       ...
747  US-2026-101322  340.704  -34.0704
748  US-2026-118885  393.568  -44.2764
749  US-2026-158526  300.980   87.2842
750  US-2026-118885  302.376   22.6782
751  US-2026-143259  323.136   12.1176

[752 rows x 3 columns]

In [33]:
pd.read_sql("SELECT \"Order ID\", \"Customer Name\", Sales, ROW_NUMBER() OVER(PARTITION BY \"Customer Name\" ORDER BY Sales DESC) AS rowno FROM superstore" ,conn)

            Order ID       Customer Name    Sales  rowno
0     US-2025-140935       Aaron Bergman  341.960      1
1     US-2023-156587       Aaron Bergman  242.940      2
2     US-2025-140935       Aaron Bergman  221.980      3
3     US-2023-156587       Aaron Bergman   48.712      4
4     US-2023-156587       Aaron Bergman   17.940      5
...              ...                 ...      ...    ...
9006  US-2026-141481  Zuschuss Donatelli   61.440      4
9007  US-2023-143336  Zuschuss Donatelli   22.720      5
9008  US-2025-147991  Zuschuss Donatelli   16.720      6
9009  US-2025-152471  Zuschuss Donatelli   15.984      7
9010  US-2023-143336  Zuschuss Donatelli    8.560      8

[9011 rows x 4 columns]

In [34]:
pd.read_sql("SELECT Category, Sales, RANK() OVER(ORDER BY Sales DESC) AS Sales_Rank FROM superstore" ,conn)

             Category    Sales  Sales_Rank
0     Office Supplies  497.610           1
1     Office Supplies  496.860           2
2          Technology  494.982           3
3          Technology  494.970           4
4          Technology  494.970           4
...               ...      ...         ...
9006  Office Supplies    0.876        9007
9007  Office Supplies    0.852        9008
9008  Office Supplies    0.836        9009
9009  Office Supplies    0.556        9010
9010  Office Supplies    0.444        9011

[9011 rows x 3 columns]

In [35]:
pd.read_sql("SELECT \"Order Date\", Sales, LAG(Sales,1) OVER(ORDER BY \"Order Date\" DESC) AS Past_Sale FROM superstore", conn)

      Order Date    Sales  Past_Sale
0     2026-12-30  323.136        NaN
1     2026-12-30  209.300    323.136
2     2026-12-30   13.904    209.300
3     2026-12-30   52.776     13.904
4     2026-12-30   20.720     52.776
...          ...      ...        ...
9006  2023-01-05   19.536    391.980
9007  2023-01-04    3.540     19.536
9008  2023-01-04   11.784      3.540
9009  2023-01-04  272.736     11.784
9010  2023-01-03   16.448    272.736

[9011 rows x 3 columns]

In [37]:
pd.read_sql("SELECT \"Order Date\", Sales, LEAD(Sales,1) OVER(ORDER BY \"Order Date\") AS next_Sale FROM superstore", conn)

      Order Date    Sales  next_Sale
0     2023-01-03   16.448      3.540
1     2023-01-04    3.540     11.784
2     2023-01-04   11.784    272.736
3     2023-01-04  272.736     19.536
4     2023-01-05   19.536      5.480
...          ...      ...        ...
9006  2026-12-30   52.776     20.720
9007  2026-12-30   20.720      3.024
9008  2026-12-30    3.024     90.930
9009  2026-12-30   90.930      3.024
9010  2026-12-30    3.024        NaN

[9011 rows x 3 columns]

In [48]:
cursor.execute("""
CREATE VIEW Sales_view AS
SELECT Category,
       SUM(Sales) AS Total_Sales,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
""")
conn.commit()

In [49]:
pd.read_sql("SELECT * FROM Sales_view", conn)

          Category  Total_Sales  Total_Profit
0        Furniture  253368.5264    -2053.9491
1  Office Supplies  349183.1640    68080.8211
2       Technology  230456.6190    35821.6015

<b>Business Question 1:</b>
Top 5 Products by Sales

In [52]:
query = """

SELECT

"Product Name",

SUM(Sales) AS TotalSales

FROM superstore

GROUP BY "Product Name"

ORDER BY TotalSales DESC

LIMIT 5;

"""

pd.read_sql(query, conn)

                                       Product Name  TotalSales
0                        KI Adjustable-Height Table    4305.071
1   Global Wood Trimmed Manager's Task Chair, Khaki    3621.004
2        Situations Contoured Folding Chairs, 4/Set    2959.866
3         Global High-Back Leather Tilter, Burgundy    2841.069
4  Nortel Meridian M3904 Professional Digital phone    2802.618

<b>Insight</b>

These products contribute the most revenue and can be prioritized for promotions.

<b>Business Question 2:</b>
Monthly Sales Trend

In [54]:
query = """

SELECT

strftime('%Y-%m',"Order Date") AS Month,

SUM(Sales) AS TotalSales

FROM superstore

GROUP BY Month

ORDER BY Month;

"""

pd.read_sql(query, conn)

      Month  TotalSales
0   2023-01   5719.3150
1   2023-02   3263.6720
2   2023-03  12780.2960
3   2023-04  11421.1910
4   2023-05  11737.6050
5   2023-06  10584.7006
6   2023-07  11024.2770
7   2023-08  13963.4925
8   2023-09  21589.5868
9   2023-10  14656.0430
10  2023-11  23132.7797
11  2023-12  24009.3355
12  2024-01   5881.8740
13  2024-02   5063.5290
14  2024-03  11109.1816
15  2024-04  13167.9905
16  2024-05  10922.6740
17  2024-06  10842.2570
18  2024-07  13015.7570
19  2024-08  12711.4842
20  2024-09  20466.3080
21  2024-10  15399.6980
22  2024-11  27483.3603
23  2024-12  28084.5840
24  2025-01   8796.7970
25  2025-02   9152.2500
26  2025-03  15562.3860
27  2025-04  12855.8120
28  2025-05  16425.5600
29  2025-06  18954.1840
30  2025-07  16437.2680
31  2025-08  13840.8078
32  2025-09  28844.1815
33  2025-10  15520.4610
34  2025-11  30624.2540
35  2025-12  31892.5280
36  2026-01  12657.7030
37  2026-02  10470.4194
38  2026-03  22905.4688
39  2026-04  16047.8786
40  2026-05  20763.4354
41  2026-06  21425.2112
42  2026-07  20787.6830
43  2026-08  18633.0920
44  2026-09  37362.2620
45  2026-10  22361.1602
46  2026-11  36300.6960
47  2026-12  36355.8188

<b>Insight</b>

Sales fluctuate across months, indicating seasonal trends.

<B>Business Question 3:</B>
Customer Segmentation by Spend

In [55]:
query = """

SELECT

Segment,

SUM(Sales) AS TotalSales

FROM superstore

GROUP BY Segment

ORDER BY TotalSales DESC;

"""

pd.read_sql(query, conn)

       Segment   TotalSales
0     Consumer  444072.4258
1    Corporate  243475.8098
2  Home Office  145460.0738

<b>Insight</B>

Identify which customer segment contributes the highest sales.

<b>Business Question 4:</b>
Total Profit by Category

In [57]:
query = """

SELECT

Category,

SUM(Profit) AS TotalProfit

FROM superstore

GROUP BY Category

ORDER BY TotalProfit DESC;

"""

pd.read_sql(query, conn)

          Category  TotalProfit
0  Office Supplies   68080.8211
1       Technology   35821.6015
2        Furniture   -2053.9491

<b>Business Question 5:</b>
Top 10 Customers by Sales

In [59]:
query = """

SELECT

"Customer Name",

SUM(Sales) AS TotalSales

FROM superstore

GROUP BY "Customer Name"

ORDER BY TotalSales DESC

LIMIT 10;

"""

pd.read_sql(query, conn)

     Customer Name  TotalSales
0       Paul Prost    4196.928
1  Laura Armstrong    3751.798
2     Greg Guthrie    3384.132
3     Ken Lonsdale    3371.691
4         John Lee    3338.352
5    William Brown    3299.140
6    Denny Blanton    3148.234
7      Chuck Clark    3052.138
8     Noel Staavos    2964.823
9      Rick Wilson    2879.891

<b>Business Question 6</b>
Products with Negative Profit

In [60]:
query = """

SELECT

"Product Name",

Profit

FROM superstore

WHERE Profit < 0

ORDER BY Profit;

"""

pd.read_sql(query, conn)

                                           Product Name     Profit
0                   Hoover Upright Vacuum With Dirt Cup -1181.2824
1     3.6 Cubic Foot Counter Height Office Refrigerator  -766.0120
2          GBC ProClick 150 Presentation Binding System  -729.9138
3                   Okidata MB491 Multifunction Printer  -643.7100
4       StarTech.com 10/100 VDSL2 Ethernet Extender Kit  -559.3560
...                                                 ...        ...
1633               SanDisk Cruzer 16 GB USB Flash Drive    -0.3444
1634          Tensor Brushed Steel Torchiere Floor Lamp    -0.3398
1635         Kingston Digital DataTraveler 16GB USB 2.0    -0.2685
1636           Acco Perma 3000 Stacking Storage Drawers    -0.2098
1637         Kingston Digital DataTraveler 16GB USB 2.0    -0.0895

[1638 rows x 2 columns]

<b>Business Question 7:</b>
Average Discount by Category

In [61]:
query = """

SELECT

Category,

AVG(Discount) AS AvgDiscount

FROM superstore

GROUP BY Category;

"""

pd.read_sql(query, conn)

          Category  AvgDiscount
0        Furniture     0.174994
1  Office Supplies     0.158585
2       Technology     0.127546

<b>Business Question 8:</b>
Number of Orders by Region

In [62]:
query = """

SELECT

Region,

COUNT(*) AS TotalOrders

FROM superstore

GROUP BY Region

ORDER BY TotalOrders DESC;

"""

pd.read_sql(query, conn)

    Region  TotalOrders
0     West         2872
1     East         2648
2  Central         2074
3    South         1417

<b>Business Question 9:</b>
State-wise Sales

In [64]:
query = """

SELECT

"State/Province",

SUM(Sales) AS TotalSales

FROM superstore

GROUP BY "State/Province"

ORDER BY TotalSales DESC;

"""

pd.read_sql(query, conn)

               State/Province   TotalSales
0                  California  175475.7375
1                    New York   92379.4070
2                       Texas   71672.9344
3                Pennsylvania   45628.6270
4                  Washington   41245.3560
5                        Ohio   37495.3080
6                    Illinois   36821.0430
7                     Florida   27593.4735
8                    Michigan   25238.8160
9                     Arizona   20945.1490
10                   Virginia   18648.0900
11             North Carolina   18502.5750
12                    Georgia   17660.3000
13                   Colorado   13704.3630
14                  Tennessee   12362.2670
15              Massachusetts   12064.3520
16                     Oregon   11280.6590
17                    Indiana   11194.0400
18                 New Jersey   11166.2920
19                   Kentucky   10794.7400
20                  Wisconsin   10554.0300
21                   Delaware    9568.1490
22                   Maryland    9057.8820
23                   Oklahoma    7116.8900
24                Connecticut    6387.2270
25                  Minnesota    6151.6500
26                   Arkansas    5298.2300
27                Mississippi    5198.1800
28                   Missouri    4929.4400
29                    Alabama    4408.1500
30               Rhode Island    4215.8100
31                       Utah    3973.1760
32                    Ontario    3883.5500
33                     Quebec    3826.9600
34             South Carolina    3469.1800
35                  Louisiana    3146.2100
36                     Kansas    2914.3100
37                 New Mexico    2758.8320
38                    Alberta    2599.6700
39                      Idaho    2557.6760
40              New Hampshire    2492.5600
41                     Nevada    2405.9320
42                   Nebraska    2333.9100
43                       Iowa    1986.9400
44           British Columbia    1726.6580
45                    Montana    1463.3820
46               South Dakota    1315.5600
47                      Maine    1270.5300
48       Prince Edward Island    1087.9160
49              West Virginia     536.4800
50  Newfoundland and Labrador     515.2000
51                    Vermont     407.2900
52                   Manitoba     404.2620
53                Nova Scotia     382.1440
54              New Brunswick     225.6960
55       District of Columbia     217.5700
56               North Dakota     215.1500
57               Saskatchewan     132.3980

<b>Business Question 10:</b>
Average Sales per Order

In [65]:
query = """

SELECT

AVG(Sales) AS AverageSales

FROM superstore;

"""

pd.read_sql(query, conn)

   AverageSales
0     92.443492

In [6]:
from db_utils import run_query

In [7]:
query = """

SELECT

Category,

SUM(Sales) AS TotalSales

FROM superstore

GROUP BY Category;

"""

run_query(query)

          Category   TotalSales
0        Furniture  253368.5264
1  Office Supplies  349183.1640
2       Technology  230456.6190